version: '3'

networks:
  net:
    driver: bridge

services:
  apiservice:
    image: apiservice
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped 
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
